spring:
  application:
    name: eureka-registry
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  #dont self register
    fetch-registry: false   # dont fetch you are a registry
    service-url:
      defaultZone: http://localhost:8761/eureka